# Generated by Django 3.0.5 on 2020-04-24 06:36

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200424_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='servi',
            field=models.CharField(max_length=200, verbose_name=core.models.Servicio),
        ),
    ]
