# Generated by Django 3.0.5 on 2020-04-25 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200424_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='servi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Servicio', verbose_name='Servicio'),
        ),
    ]
