# Generated by Django 3.0.5 on 2020-05-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200425_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
